services:
  - type: web
    name: konnectmedia-api
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: PORT
        value: 4000
